language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "OfqRkPfSzBeU288mu0hEktEoWMZxxcYJN9BzrDrrXgTPCev5C7URonk+71pCB3L5+pI8fD/mBanhqFgClpe1tJdmt0m6BJ6woLMSNJT/1jdxX6C55gIaKPfutO0Of1GQ8K6ibHnlgrgsk/mGwRDH01u3k0qkL3saPNrVlBgmC5E="
    - GIT_COMMITTER_NAME=RikaFujiwara
    - GIT_COMMITTER_EMAIL=rika.fujiwara@allcreator.net
    - GIT_AUTHOR_NAME=RikaFujiwara
    - GIT_AUTHOR_EMAIL=rika.fujiwara@allcreator.net

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - travis_wait . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
