language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false
dist: trusty

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
    - secure: "cb32rUp2l+Zd991n/6fY18wudLW0EjqqqlvxpKMWZOUaJ6dS5+R+IcoV5Oo94TNUEgzOQ/7Ldp5PW+qGg0S5EDyQOHtLp7kmmGy9ST7EL0QNyWyfSGXl9FUCqKd/fP3WZVx8ci6MgfUtj5DfamqjRctpJy4uQapbZwtUDQWweGY="
    - GIT_COMMITTER_NAME=RikaFujiwara
    - GIT_COMMITTER_EMAIL=rika.fujiwara@allcreator.net
    - GIT_AUTHOR_NAME=RikaFujiwara
    - GIT_AUTHOR_EMAIL=rika.fujiwara@allcreator.net

matrix:
  allow_failures:
    # PHP 7.4 testing is allowed to fail because the GD extension and ZipArchive is not packaged on Travis CI yet.
    # See https://travis-ci.community/t/some-extensions-are-missing-in-php-7-4-0-zip-gmp-sodium/6320/9
    - php: 7.4

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
